### ISSUE TITLE
Reprompt even on full consent? 

### ISSUE THREAD

**Issue by DavideMoney** [digi-trust/cmp#131]
Some users are reporting me that the cmp message reprompt  even if they gave the full consent  days before.

It also happened to me once but I was not able to reproduce the problem.

**Comment by dragu** [comment]
@DavideMoney do you store your consents globally (storeConsentGlobally config option)? I bet you do. We have the same issue. It happens when website from globalConsentLocation config is unavailable (default cdn.digitrust.mgr.consensu.org).

If user get timeout on cdn.digitrust.mgr.consensu.org, CMP can't read consent and show the popup again. It is very annoying for users.

This is how it should be fixed:

1. CMP stores a consent on local domain ALWAYS
2. If storeConsentGlobally is enabled, consent is stored also on domain from globalConsentLocation
3. Consent is read from local domain FIRST, if there is no cookie it should check on globalConsentLocation
4. If there is a consent on local domain and there is no consent on globalConsentLocation, it should be send to the globalConsentLocation
5. If there is a consent on globalConsentLocation and there is no consent on local domain, it should be created

Unless digi-trust do it, it will be veeeeeeeery annoying for everyone using storeConsentGlobally.

**Comment by DavideMoney** [comment]
@dragu Yes we store consent globally. 
@SupahNickie Do you confirm the reprompt scenario on timeout? 

If so is it possible to fix it as proposed by @dragu ?

Thanks

**Comment by DavideMoney** [comment]
@dragu Maybe the scenario is not my case. 

My colleague just showed me one of our webisite where we do have the consent read correctly  and the banners start to appear on the page (we begin the rendering on 
`   window.__cmp('getConsentData', null, function (result) {  //render adunits...})`
), but the cmp appear anyway... really confused

**Comment by dragu** [comment]
@DavideMoney are ads rendering before you confirm an agreement? It is normal that callback is running right after your agreement.

To reproduce this bug change globalConsentLocation to other value, for example

> //example.com/portal.html

![zaznaczenie_014](https://user-images.githubusercontent.com/2284006/41720899-be0e73b0-7564-11e8-8ef9-3aad05bd7ea0.png)

**Comment by SupahNickie** [comment]
@DavideMoney and @dragu , thank you for this report and the proposed solution. I have presented it to the product owners in the working group and will update this ticket when I hear back about what sort of solution we will build out.

**Comment by dragu** [comment]
@DavideMoney so I am afraid it is something else. Enable debugging and check the console, maybe you'll find more details then.

@SupahNickie thanks

**Comment by DavideMoney** [comment]
@SupahNickie  Thanks for the explanation. That possibly explain the issue for me.

@dragu If you don't have any other comments and/or questions I consider solved the issue and close. Please let me know
