### ISSUE TITLE
Updated Node version.

### ISSUE THREAD

**Issue by edudix** [digi-trust/cmp#141]
Hi,
We´re getting the following error when running `yarn install`.
It seems our node version is an updated one. Is there any solution for that.
Many thanks!!!

![captura de pantalla 2018-07-17 a las 12 01 15](https://user-images.githubusercontent.com/26487838/42813462-651f56ea-89c1-11e8-853e-a9a4efcec90d.png)

**Comment by SupahNickie** [comment]
We're running the long term support version of Node, which as of right now is 8.11.3. For maximum stability, I think we're going to keep it where it is, but I will bring this up with the working group. Regardless of which way we go, I will update the package.json file to reflect the version.

Thanks for raising this 👍

**Comment by edudix** [comment]
Hello Nicholas,
Nice to meet you and thanks for your answer.
Is there any other way to work with? We use NPM, is there any command to build it.
BR regards




Eduardo Orusco
Director Servicio al Cliente y 
Desarrollo de Negocio	
eorusco@marzomarketing.com
www.marzo.com.es
+34 91 853 32 92
+34 667 879 612

**Comment by SupahNickie** [comment]
Hello, and nice to meet you too! Since we're going to be using the long term support version of Node, unfortunately we're not going to be using a version that is supported by that one package (due to stability). However, I highly recommend using Node Version Manager ( https://github.com/creationix/nvm#installation ) which you can use to install multiple versions of Node on the same computer and toggle between them. This will make it easy to develop against this project because you can simply install that tool, download the LTS version of Node, run `npm install` and then run our dev environment.
