### ISSUE TITLE
CMP not working

### ISSUE THREAD

**Issue by panxpiotr** [digi-trust/cmp#147]
Hi,

The code of your CMP provided by AdForm stopped working. It doesn't load:

> cmp.complete.bundle.js:1 Possible Unhandled Promise Rejection: TypeError: Cannot read property 'then' of undefined

**Comment by SupahNickie** [comment]
Thank you for your report @panxpiotr ! The code change to fix this issue can be seen at https://github.com/digi-trust/cmp/commit/7d4f79476a2f46b3e26052025b4325d5836be8a9 and we have deployed the change up to production. It may take some time for our CDN to pick up the changes though (at most 24 hours). If the issue comes up again 24 hours from now, please reopen this issue. Thanks!
