### ISSUE TITLE
Support standardised content in languages outlined by IAB EU policy doc

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#21]
Summary:
Support standardised messaging in the CMP in the following languages:
Bulgarian, Czech, Croatian, Danish, German, Greek, English, Spanish, Estonian, Finnish, French, Hungarian, Icelandic, Irish, Italian, Lithuanian, Latvian, Malti, Dutch, Norwegian, Polish, Portuguese, Romanian, Slovak, Slovene, Swedish and Turkish
The user must be shown messaging in the correct language based on their browser/device language

Acceptance Criteria:
As a CMP, I must support standardised consent messaging outlined in the IAB EU Consent and Transparency policy
As a publisher, I should expect that the user should be shown messaging in the correct language based on their browser/device language
As a user, I should expect to be shown consent messaging in a language familiar to me and the content I'm consuming

Details:
The Digitrust group will provide one set of wording (and the translations)

**Comment by SupahNickie** [comment]
Going to close this since the ticket is quite broad and not quite actionable anymore. We will have to keep in mind any new wording at this point will have to get translated into the currently supported languages. There is also currently a ticket to get translations for these outstanding phrases: https://github.com/digi-trust/cmp/issues/101
