### ISSUE TITLE
Placeholder: Support GDPR Consent passing for URL-based services

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#33]
This is a placeholder for the work required to support the industry-standard proposal for passing consent signals (outside of the OpenRTB fields) suitable for direct HTTP called services.
https://docs.google.com/document/d/1g3y9qQ-F1sMbwRG9Bbw_tD9aXGlylG36Jc1Miwx2pUk/edit#

**Comment by SupahNickie** [comment]
We have cases already where a publisher is using a CMP that is hosted on the provider's site and does a redirect after consent is given. We have JS on the page that will not be able to work because technically there is no CMP on the publisher's page and thus we cannot access the consent strings through the IAB defined functions. 

I think it's possible to build a URL-based consent passer that also can handle this case as well. For instance, if there's no redirect_url parameter, we just return the consent string back to the request so that when our tracking services hit this endpoint, we are still able to supply the global vendor consent string.

**Comment by samtingleff** [comment]
I _think_ this could be possible
```
- lambda @edge function in node/java/etc
- use the CloudFront-Viewer-Country header for geo resolution
- parse the global consent cookie, parse inputs, check geo, send redirect
```

However
- need to validate that `CloudFront-Viewer-Country` is sent to backend for @edge
- possible concerns around operating an open redirect (also an issue with the spec)
