### ISSUE TITLE
Investigate viability of detecting whether a user is located in the EU at the edge

### ISSUE THREAD

**Issue by anissaconnor** [digi-trust/cmp#39]
Summary
Investigate viability of detecting whether a user is located in the EU at the edge

Why?
For those publishers that don't want to show the CMP to all site visitor, offer them the option to show it to users located in the EU. Have this dynamically influence the input of the 'gdprapplies' variable. If the user has chosen for the CMP to detect whether the user is located in the EU, 'hasglobalscope' should be set to false.

Acceptance Criteria:
As a publisher, I should be able to configure the CMP to detect whether a user is located in the EU to inform whether the consent window should be triggered.

**Comment by SupahNickie** [comment]
Yes, that's exactly the sort of thing that Peter Davies with Rakuten built. I'm totally fine with using it if you guys are. 👍 

The one thing that I worry about is the cost of offering something like this to however many pubs wanting to use our CMP and hitting that endpoint n times a day with whatever traffic they get. If the onus is on us to pay for the throughput, that could get spendy pretty quickly.

**Comment by samtingleff** [comment]
We're already expecting cmp resources to serve off of this CDN for n publishers. The cost of 1 more resource is pretty minimal (if one more request is required at all; maybe we can grab the header from a resource which would be requested anyway).

I think I'm more worried about illegitimate usage. That is, publishers which are not cmp customers making an XHR request to some asset in order to get free geoip data. Perhaps we can protect from this with smart usage of CORS headers.

**Comment by SupahNickie** [comment]
Covered by https://github.com/digi-trust/cmp/issues/6 and PR https://github.com/digi-trust/cmp/pull/45
